title: The WebAuthN Wall of Shame
description: >-
  A list of vendors that do not support WebAuthN, preventing
  their customers/users from using phishing-resistant authenticators.

url: https://fido.fail/

host: 0.0.0.0

theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true

collections:
  - vendors
