title: The WebAuthN Wall of Shame
description: >-
  A list of vendors that do not support WebAuthn, 
  denying their customers/users phishing-resistance .

url: https://nickborgers.github.io/webauthn-wall-of-shame

host: 0.0.0.0

theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true

collections:
  - vendors
