title: The WebAuthn Wall of Shame
description: >-
  A list of products that prevent use of WebAuthn during SSO, preventing
  their customers/users from using phishing-resistant authenticators.

url: https://fido.fail/

host: 0.0.0.0

theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true

collections:
  - vendors
